name: Update Docs Config
on:
  repository_dispatch:
    types: [update-docs-config]

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      actions: read  
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get Base Config
        uses: actions/checkout@v4
        with:
          github-token: ${{ secrets.SYC_TOKEN }}
          repository: Vegetable-SYC/docs-base-config
          path: base-config  
          
      - name: Merge Config
        run: |
          python docs-base-config/update_workflow/sync_config.py \ 
            --source base-config/base_conf.py.tpl \           
            --target docs/source/conf.py                      
          
      - name: Commit Changes
        run: |
          git config --global user.name "Docs Bot"
          git config --global user.email "docs-bot@example.com"
          git add docs/source/conf.py
          git commit -m " Auto-update docs config"
          git push
